<a href="https://colab.research.google.com/github/refianP13/Data-Analyst/blob/main/Copy_of_DQLab_Number_Date_Format_%26_SubQuery.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# <b><span style='color:#0B2F9F'>Pengantar</span></b>

Dalam pengelolaan data, kemampuan untuk menampilkan informasi dengan format yang tepat serta menggali data secara mendalam menjadi hal yang sangat penting. Format angka dan tanggal membantu memastikan data tersaji secara konsisten, mudah dibaca, dan sesuai konteks, sehingga hasil analisis lebih akurat dan informatif. Sementara itu, penggunaan subquery memungkinkan pengambilan data secara lebih fleksibel dan efisien, dengan cara memecah proses pencarian menjadi langkah-langkah yang lebih terarah. Dengan memahami kedua konsep ini, seseorang dapat mengolah data dengan lebih rapi, melakukan analisis yang lebih mendalam, serta menghasilkan informasi yang lebih bermakna dan dapat diandalkan.

# <b><span style='color:#0B2F9F'>Set up</span></b>

Dibutuhkan proses autentikasi dari Google Colab ke Google Big Query. Ikuti langkah berikut https://drive.google.com/file/d/1gW8alZ_PrvcrsieqWCHOR4ssLI_25BRc/view untuk detail step-by-step nya

In [1]:
# Import library yang dibutuhkan
from google.colab import auth, data_table
from google.cloud import bigquery
from pandas_gbq import to_gbq

# Proses autentikasi akun
auth.authenticate_user()
print('Authenticated')

Authenticated

In [2]:
# Buat BigQuery client
project_id = 'dqlabs-project'
client = bigquery.Client(project = project_id)

Sebagai Data Engineer, Antara (Jr. Data Engineer di DQPizza) ditugaskan untuk membuat data mart untuk kebutuhan detail transaksi. Dengan memanfaatkan relasi antar table, Antara mengeksekusi suatu perintah  untuk membuat table tbl_all_transaction (sebuah tabel fact yang berisi data transaksi secara rinci, mencakup ukuran-ukuran kuantitatif seperti jumlah, harga, total nilai transaksi, dan lain sebagainya) hingga terbentuklah tabel tbl_all_transaction.

<br>
<code>SELECT * FROM .dqpizza.tbl_all_transaction</code>
<br><br>
<img src="https://raw.githubusercontent.com/bachtiyarma/Material/main/Image/Materi-SQL/SQL%20-%20tbl_all_transaction.png" width="30%">

Data dibawah (tbl_all_transaction) akan digunakan pada modul ini

In [3]:
%%bigquery --project {project_id} --verbose
CREATE TABLE IF NOT EXISTS dqpizza.tbl_all_transaction AS
SELECT
  order_id,
  order_details_id,
  customer_id,
  order_maker_id,
  pizza_name,
  pizza_category,
  pizza_size,
  pizza_price,
  pizza_production_cost,
  quantity,
  order_date,
  order_time,
  completion_time,
  is_complain,
  complain_detail
FROM dqlabproject-2026.dqpizza.tbl_all_transaction

Executing query with job ID: 3b9cd07b-1192-44e1-812c-60e04915cca2
Query executing: 3.38s
Job ID 3b9cd07b-1192-44e1-812c-60e04915cca2 successfully executed

Query is running:   0%|          |

Empty DataFrame
Columns: []
Index: []

In [4]:
%%bigquery --project {project_id} --verbose

SELECT * FROM dqpizza.tbl_all_transaction

Executing query with job ID: a1cd12d7-be09-461b-8633-59a120762599
Query executing: 1.90s
Job ID a1cd12d7-be09-461b-8633-59a120762599 successfully executed

Query is running:   0%|          |

Downloading:   0%|          |

,order_id,order_details_id,customer_id,order_maker_id,pizza_name,pizza_category,pizza_size,pizza_price,pizza_production_cost,quantity,order_date,order_time,completion_time,is_complain,complain_detail
0,TRX008021,TRXD018266,CUST009740,EMP000208,THE PEPPERONI PIZZA,CLASSIC,S,78975.0,62937.0,1,2025-05-15,11:52:10,12:09:48,0,None
1,TRX004761,TRXD010874,CUST007768,EMP000208,THE PEPPERONI PIZZA,CLASSIC,S,78975.0,62937.0,1,2025-03-21,18:10:58,18:34:26,0,None
2,TRX016561,TRXD037506,CUST009740,EMP000208,THE PEPPERONI PIZZA,CLASSIC,S,78975.0,62937.0,1,2025-10-07,12:44:22,13:04:24,0,None
3,TRX000734,TRXD001645,CUST003549,EMP000208,THE PEPPERONI PIZZA,CLASSIC,S,78975.0,62937.0,1,2025-01-12,20:00:30,20:27:49,0,None
4,TRX007218,TRXD016397,CUST004945,EMP000208,THE PEPPERONI PIZZA,CLASSIC,S,78975.0,62937.0,1,2025-05-01,18:00:53,18:18:17,0,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48614,TRX019319,TRXD043953,CUST007656,EMP000756,THE BRIE CARRE PIZZA,SUPREME,S,191565.0,170505.0,1,2025-11-26,13:35:19,13:59:54,0,None
48615,TRX000261,TRXD000593,CUST007085,EMP000756,THE BRIE CARRE PIZZA,SUPREME,S,191565.0,170505.0,1,2025-01-05,12:38:29,13:05:07,0,None
48616,TRX001581,TRXD003564,CUST009381,EMP000756,THE GREEK PIZZA,CLASSIC,XXL,291195.0,260738.0,1,2025-01-27,16:28:38,16:54:32,0,None
48617,TRX016753,TRXD037944,CUST004945,EMP000756,THE GREEK PIZZA,CLASSIC,XXL,291195.0,260738.0,1,2025-10-10,17:54:55,18:06:01,0,None
48618,TRX002813,TRXD006366,CUST006714,EMP000756,THE GREEK PIZZA,CLASSIC,XXL,291195.0,260738.0,1,2025-02-16,18:15:02,18:29:26,0,None

# <b>A. <span style='color:#0B2F9F'><code>Data Type</code></span></b>

Data type dalam BigQuery adalah cara untuk mendefinisikan jenis data yang akan disimpan dalam tabel. Setiap kolom dalam tabel memiliki tipe data tertentu, yang menentukan apa yang dapat disimpan di kolom tersebut dan bagaimana data tersebut dapat diproses. Memahami tipe data ini penting untuk desain skema yang efisien dan untuk memastikan bahwa kueri dapat dijalankan dengan optimal.

<br>
<img src="https://hackolade.com/help/lib/BigQuery%20data%20types%20table.png" width="40%">

docs : <i><a href="https://cloud.google.com/bigquery/docs/reference/standard-sql/data-types">https://cloud.google.com/bigquery/docs/reference/standard-sql/data-types</a></i>

# <b>B. <span style='color:#0B2F9F'><code>Operasi Tipe Data Numerik</code></span></b>

Dalam SQL, tipe data numerik digunakan untuk menyimpan nilai angka dan dapat dikelompokkan menjadi beberapa jenis sesuai peruntukannya (INT, FLOAT, NUMERIC, dll). Selain itu pada tipe data Numerik juga dapat dilakukan operasi matematis diantaranya :
<ol>
    <li>Operasi Aritmatika</li>
    <li>Fungsi Matematis</li>
    <li>Agregasi</li>
</ol>

## <b>B.1. <span style='color:#0B2F9F'><code>Operasi Aritmatika</code></span></b>
SQL mendukung operasi dasar aritmatika seperti penjumlahan, pengurangan, perkalian, pembagian dan modulo.

<img src="https://mazamanbd.wordpress.com/wp-content/uploads/2014/09/dd.jpg"><br><br>

Untuk dapat menerapkannya pada sebuah tabel gunakan contoh format berikut

<img src="https://raw.githubusercontent.com/bachtiyarma/Material/refs/heads/main/Image/Materi-SQL/SQL%20-%20OperasiAritmatika.png" width="50%">

<i>docs : <a href="https://cloud.google.com/bigquery/docs/reference/standard-sql/operators">https://cloud.google.com/bigquery/docs/reference/standard-sql/operators</a></i>

#### <i><b><span style='color:#55679C'>Quest</span> : Pada tabel tbl_all_transaction, tampilkan semua kolom dan tambahkan satu kolom 'total_price' yang merupakan hasil perkalian antara harga dengan kuantitas (terbeli)! Urutkan berdasarkan kuantitas paling besar hingga ke terkecil </b></i>

In [5]:
%%bigquery --project {project_id} --verbose

SELECT *, (pizza_price * quantity) AS total_price
FROM dqpizza.tbl_all_transaction
ORDER BY quantity DESC

Executing query with job ID: 4d7a915c-04b4-4087-ac3d-3ef4b8fa3dfb
Query executing: 1.72s
Job ID 4d7a915c-04b4-4087-ac3d-3ef4b8fa3dfb successfully executed

Query is running:   0%|          |

Downloading:   0%|          |

,order_id,order_details_id,customer_id,order_maker_id,pizza_name,pizza_category,pizza_size,pizza_price,pizza_production_cost,quantity,order_date,order_time,completion_time,is_complain,complain_detail,total_price
0,TRX005264,TRXD011977,CUST004837,EMP000286,THE BIG MEAT PIZZA,CLASSIC,S,97200.0,81567.0,4,2025-03-30,13:24:35,13:35:43,0,None,388800.0
1,TRX008286,TRXD018876,CUST004105,EMP000437,THE BIG MEAT PIZZA,CLASSIC,S,97200.0,81567.0,4,2025-05-19,12:42:46,13:11:40,0,None,388800.0
2,TRX015674,TRXD035497,CUST006814,EMP000302,THE CALIFORNIA CHICKEN PIZZA,CHICKEN,L,168075.0,118989.0,4,2025-09-19,14:16:35,14:40:53,0,None,672300.0
3,TRX018845,TRXD042847,CUST007150,EMP000756,THE BARBECUE CHICKEN PIZZA,CHICKEN,M,135675.0,99468.0,3,2025-11-18,12:25:12,12:50:38,0,None,407025.0
4,TRX000144,TRXD000342,CUST006964,EMP000231,THE BARBECUE CHICKEN PIZZA,CHICKEN,M,135675.0,99468.0,3,2025-01-03,13:44:28,14:06:42,0,None,407025.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48614,TRX019319,TRXD043953,CUST007656,EMP000756,THE BRIE CARRE PIZZA,SUPREME,S,191565.0,170505.0,1,2025-11-26,13:35:19,13:59:54,0,None,191565.0
48615,TRX000261,TRXD000593,CUST007085,EMP000756,THE BRIE CARRE PIZZA,SUPREME,S,191565.0,170505.0,1,2025-01-05,12:38:29,13:05:07,0,None,191565.0
48616,TRX001581,TRXD003564,CUST009381,EMP000756,THE GREEK PIZZA,CLASSIC,XXL,291195.0,260738.0,1,2025-01-27,16:28:38,16:54:32,0,None,291195.0
48617,TRX016753,TRXD037944,CUST004945,EMP000756,THE GREEK PIZZA,CLASSIC,XXL,291195.0,260738.0,1,2025-10-10,17:54:55,18:06:01,0,None,291195.0
48618,TRX014557,TRXD032931,CUST008951,EMP000437,THE MEDITERRANEAN PIZZA,VEGGIE,S,97200.0,74844.0,1,2025-08-31,18:45:10,19:02:02,0,None,97200.0

#### <i><b><span style='color:#55679C'>Quest</span> : Selain total price, tambahkan juga total profit yang didapat tiap transaksi! (Lanjutkan hasil query quest diatas) </b></i>

In [7]:
%%bigquery --project {project_id} --verbose

SELECT *, (pizza_price * quantity) AS total_price, (pizza_price - pizza_production_cost) * quantity AS total_profit
FROM dqpizza.tbl_all_transaction
ORDER BY quantity DESC

Executing query with job ID: 191fe6c5-f0ee-4254-a11b-6771f76fda46
Query executing: 1.61s
Job ID 191fe6c5-f0ee-4254-a11b-6771f76fda46 successfully executed

Query is running:   0%|          |

Downloading:   0%|          |

,order_id,order_details_id,customer_id,order_maker_id,pizza_name,pizza_category,pizza_size,pizza_price,pizza_production_cost,quantity,order_date,order_time,completion_time,is_complain,complain_detail,total_price,total_profit
0,TRX005264,TRXD011977,CUST004837,EMP000286,THE BIG MEAT PIZZA,CLASSIC,S,97200.0,81567.0,4,2025-03-30,13:24:35,13:35:43,0,None,388800.0,62532.0
1,TRX008286,TRXD018876,CUST004105,EMP000437,THE BIG MEAT PIZZA,CLASSIC,S,97200.0,81567.0,4,2025-05-19,12:42:46,13:11:40,0,None,388800.0,62532.0
2,TRX015674,TRXD035497,CUST006814,EMP000302,THE CALIFORNIA CHICKEN PIZZA,CHICKEN,L,168075.0,118989.0,4,2025-09-19,14:16:35,14:40:53,0,None,672300.0,196344.0
3,TRX018845,TRXD042847,CUST007150,EMP000756,THE BARBECUE CHICKEN PIZZA,CHICKEN,M,135675.0,99468.0,3,2025-11-18,12:25:12,12:50:38,0,None,407025.0,108621.0
4,TRX000144,TRXD000342,CUST006964,EMP000231,THE BARBECUE CHICKEN PIZZA,CHICKEN,M,135675.0,99468.0,3,2025-01-03,13:44:28,14:06:42,0,None,407025.0,108621.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48614,TRX019319,TRXD043953,CUST007656,EMP000756,THE BRIE CARRE PIZZA,SUPREME,S,191565.0,170505.0,1,2025-11-26,13:35:19,13:59:54,0,None,191565.0,21060.0
48615,TRX000261,TRXD000593,CUST007085,EMP000756,THE BRIE CARRE PIZZA,SUPREME,S,191565.0,170505.0,1,2025-01-05,12:38:29,13:05:07,0,None,191565.0,21060.0
48616,TRX001581,TRXD003564,CUST009381,EMP000756,THE GREEK PIZZA,CLASSIC,XXL,291195.0,260738.0,1,2025-01-27,16:28:38,16:54:32,0,None,291195.0,30457.0
48617,TRX016753,TRXD037944,CUST004945,EMP000756,THE GREEK PIZZA,CLASSIC,XXL,291195.0,260738.0,1,2025-10-10,17:54:55,18:06:01,0,None,291195.0,30457.0
48618,TRX014557,TRXD032931,CUST008951,EMP000437,THE MEDITERRANEAN PIZZA,VEGGIE,S,97200.0,74844.0,1,2025-08-31,18:45:10,19:02:02,0,None,97200.0,22356.0

#### <i><b><span style='color:#55679C'>Quest</span> : Bagaimana dengan customer paling loyal? Paling loyal diukur dari banyak profit restaurant yang dihasilkan. Tampilkan customer_id, total_frequency (berapa kali pembelian dalam setahun) dan total_profit yang diperoleh perusahaan, kelompokkan tiap customer_id! Urutkan berdasarkan customer_id dengan profit paling tinggi ke paling rendah! </b></i>

In [13]:
%%bigquery --project {project_id} --verbose

SELECT
  customer_id,
  COUNT(DISTINCT order_id) AS total_frequency,
  SUM((pizza_price - pizza_production_cost) * quantity) AS total_profit,
  SUM(pizza_price * quantity) AS total_revenue
FROM dqpizza.tbl_all_transaction
GROUP BY customer_id
ORDER BY total_profit DESC

Executing query with job ID: a2efc823-f441-42d6-8166-dd3604c55146
Query executing: 0.82s
Job ID a2efc823-f441-42d6-8166-dd3604c55146 successfully executed

Query is running:   0%|          |

Downloading:   0%|          |

    customer_id  total_frequency  total_profit  total_revenue
0    CUST006333              741    47622169.0    237372120.0
1    CUST009381              702    44017426.0    216491535.0
2    CUST007656              614    37358334.0    187758810.0
3    CUST003549              580    36914292.0    182958345.0
4    CUST006964              521    32351562.0    159938955.0
..          ...              ...           ...            ...
115  CUST008078               21     1070496.0      4916700.0
116  CUST005536               24      987714.0      5314815.0
117  CUST006892               12      858681.0      4237515.0
118  CUST003871               13      685908.0      3708990.0
119  CUST002478               17      659259.0      3369600.0

[120 rows x 4 columns]

## <b>B.2. <span style='color:#0B2F9F'><code>Fungsi Matematis</code></span></b>
SQL juga mendukung fungsi matematis dasar yang disajikan pada tabel berikut :

<table border="1">
    <thead>
        <tr>
            <th>Fungsi</th>
            <th>Deskripsi</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td><code>ABS()</code></td>
            <td>Mengambil nilai absolut</td>
        </tr>
        <tr>
            <td><code>ROUND()</code></td>
            <td>Membulatkan angka</td>
        </tr>
        <tr>
            <td><code>CEIL()</code></td>
            <td>Membulatkan ke atas</td>
        </tr>
        <tr>
            <td><code>FLOOR()</code></td>
            <td>Membulatkan ke bawah</td>
        </tr>
        <tr>
            <td><code>POW()</code></td>
            <td>Menghitung pangkat</td>
        </tr>
    </tbody>
</table>

Untuk dapat menerapkannya pada sebuah tabel gunakan contoh format berikut

<img src="https://raw.githubusercontent.com/bachtiyarma/Material/refs/heads/main/Image/Materi-SQL/SQL-FungsiMatematis.png" width="50%">

<i>docs : <a href="https://cloud.google.com/bigquery/docs/reference/standard-sql/mathematical_functions">https://cloud.google.com/bigquery/docs/reference/standard-sql/mathematical_functions</a></i>

#### <i><b><span style='color:#55679C'>Quest</span> : Sendja (Data Analyst di DQPizza) baru menyadari bahwa profit yang ia hitung pada quest sebelumnya merupakan profit sebelum pajak. Asumsikan pajak yang perlu dikeluarkan adalah 11% tiap kali transaksi. Hitung profit_before_tax, profit_after_tax dan tax_paid tiap order_id dan customer_id! Lakukan perhitungan untuk setiap transaksi yang valid (order_details_id tidak kosong)!</b></i>

Note : Bulatkan profit after tax sebanyak 2 angka dibelakang koma agar lebih rapi

In [18]:
%%bigquery --project {project_id} --verbose

SELECT
  order_id,
  customer_id,
  SUM((pizza_price - pizza_production_cost) * quantity) AS profit_before_tax,
  ROUND(SUM((pizza_price - pizza_production_cost) * quantity) * (1 - 0.11), 2) AS profit_after_tax,
  SUM((pizza_price - pizza_production_cost) * quantity) * 0.11 AS tax_paid
FROM
  dqpizza.tbl_all_transaction
WHERE
  order_details_id IS NOT NULL
GROUP BY
  order_id,
  customer_id

Executing query with job ID: 8498c19e-21ec-48a0-9e01-9d0d8ab55772
Query executing: 1.37s
Job ID 8498c19e-21ec-48a0-9e01-9d0d8ab55772 successfully executed

Query is running:   0%|          |

Downloading:   0%|          |

        order_id customer_id  profit_before_tax  profit_after_tax  tax_paid
0      TRX003947  CUST009755            16038.0          14273.82   1764.18
1      TRX013010  CUST005604            34992.0          31142.88   3849.12
2      TRX001319  CUST004212            81891.0          72882.99   9008.01
3      TRX011935  CUST004354            74034.0          65890.26   8143.74
4      TRX004103  CUST006714            88209.0          78506.01   9702.99
...          ...         ...                ...               ...       ...
21341  TRX014773  CUST009740            93069.0          82831.41  10237.59
21342  TRX003295  CUST009740            24705.0          21987.45   2717.55
21343  TRX002839  CUST009740            22761.0          20257.29   2503.71
21344  TRX003352  CUST009740            49329.0          43902.81   5426.19
21345  TRX014779  CUST009740            21060.0          18743.40   2316.60

[21346 rows x 5 columns]

# <b>C. <span style='color:#0B2F9F'><code>Operasi Tipe Data Date</code></span></b>

Dalam SQL, tipe data date digunakan untuk menyimpan atau mengoperasikan data tanggal. Tipe data tanggal dapat dilakukan operasi berikut, diantaranya :
<ol>
    <li>Menampilkan Tanggal & Waktu saat ini</li>
    <li>Menambahkan atau Mengurangi Tanggal</li>
    <li>Mendapatkan Bagian Tanggal</li>
    <li>Menghitung Selisih Tanggal</li>
</ol>

<br><b>NOTE</b><br><br>
Hal-hal yang perlu diperhatikan dalam penggunaan operasi `date` adalah :
<ul>
    <li>Format tanggal standar SQL adalah 'YYYY-MM-DD' atau tahun - bulan - tanggal, contoh : 2024-10-14 menunjukan tanggal 14 October 2024</li>
    <li>Mengakses tanggal pada SQL perlu menggunakan tanda apit petik satu, contoh : '2024-10-14'</li>
    <li>Pastikan nilai atau kolom tanggal tipe datanya adalah DATE atau TIMESTAMP, jika tidak maka bisa dikonversi menjadi <code>DATE(tanggal)</code> atau <code>TIMESTAMP(tanggal)</code></li>
</ul>

<i>docs : <a href="https://cloud.google.com/bigquery/docs/reference/standard-sql/date_functions">https://cloud.google.com/bigquery/docs/reference/standard-sql/date_functions</a></i>

## <b>C.1. <span style='color:#0B2F9F'><code>Menampilkan Tanggal & Waktu Saat Ini</code></span></b>

Untuk menampilkan tanggal dan waktu saat ini dapat menggunakan fungsi berikut
<table border="1">
    <thead>
        <tr>
            <th>Fungsi</th>
            <th>Deskripsi</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td><code>CURRENT_DATE()</code></td>
            <td>Mendapatkan Tanggal Hari ini Saja</td>
        </tr>
        <tr>
            <td><code>CURRENT_TIMESTAMP()</code></td>
            <td>Mendapatkan Tanggal & Waktu Hari ini (UTC)</td>
        </tr>
    </tbody>
</table>

UTC atau (Universal Time Coordinated) adalah waktu dasar yang tidak terpengaruh oleh zona waktu dan <i>daylight saving time</i>. UTC digunakan sebagai acuan untuk menghitung waktu di berbagai zona waktu di seluruh dunia (standar Greenwich Mean Time (London)). Selengkapnya baca <a href="https://internasional.kompas.com/read/2021/03/04/192042570/sejarah-penetapan-zona-waktu-di-dunia-hingga-usulan-penghapusannya?page=all">disini</a>.

#### <i><b><span style='color:#55679C'>Quest</span> : Tampilkan semua kolom pada tabel tbl_all_transaction dan tambahkan kolom data_collection_time sebagai kolom metadata waktu pengambilan data</b></i><br>

In [23]:
%%bigquery --project {project_id} --verbose

SELECT   *,

  CURRENT_TIMESTAMP() AS data_collection_time

FROM dqpizza.tbl_all_transaction

Executing query with job ID: 84e99c0d-c7e5-4f46-befb-b6d2279f7bcf
Query executing: 1.58s
Job ID 84e99c0d-c7e5-4f46-befb-b6d2279f7bcf successfully executed

Query is running:   0%|          |

Downloading:   0%|          |

,order_id,order_details_id,customer_id,order_maker_id,pizza_name,pizza_category,pizza_size,pizza_price,pizza_production_cost,quantity,order_date,order_time,completion_time,is_complain,complain_detail,data_collection_time
0,TRX008021,TRXD018266,CUST009740,EMP000208,THE PEPPERONI PIZZA,CLASSIC,S,78975.0,62937.0,1,2025-05-15,11:52:10,12:09:48,0,None,2026-06-15 13:39:29.394476+00:00
1,TRX004761,TRXD010874,CUST007768,EMP000208,THE PEPPERONI PIZZA,CLASSIC,S,78975.0,62937.0,1,2025-03-21,18:10:58,18:34:26,0,None,2026-06-15 13:39:29.394476+00:00
2,TRX016561,TRXD037506,CUST009740,EMP000208,THE PEPPERONI PIZZA,CLASSIC,S,78975.0,62937.0,1,2025-10-07,12:44:22,13:04:24,0,None,2026-06-15 13:39:29.394476+00:00
3,TRX000734,TRXD001645,CUST003549,EMP000208,THE PEPPERONI PIZZA,CLASSIC,S,78975.0,62937.0,1,2025-01-12,20:00:30,20:27:49,0,None,2026-06-15 13:39:29.394476+00:00
4,TRX007218,TRXD016397,CUST004945,EMP000208,THE PEPPERONI PIZZA,CLASSIC,S,78975.0,62937.0,1,2025-05-01,18:00:53,18:18:17,0,None,2026-06-15 13:39:29.394476+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48614,TRX019319,TRXD043953,CUST007656,EMP000756,THE BRIE CARRE PIZZA,SUPREME,S,191565.0,170505.0,1,2025-11-26,13:35:19,13:59:54,0,None,2026-06-15 13:39:29.394476+00:00
48615,TRX000261,TRXD000593,CUST007085,EMP000756,THE BRIE CARRE PIZZA,SUPREME,S,191565.0,170505.0,1,2025-01-05,12:38:29,13:05:07,0,None,2026-06-15 13:39:29.394476+00:00
48616,TRX001581,TRXD003564,CUST009381,EMP000756,THE GREEK PIZZA,CLASSIC,XXL,291195.0,260738.0,1,2025-01-27,16:28:38,16:54:32,0,None,2026-06-15 13:39:29.394476+00:00
48617,TRX016753,TRXD037944,CUST004945,EMP000756,THE GREEK PIZZA,CLASSIC,XXL,291195.0,260738.0,1,2025-10-10,17:54:55,18:06:01,0,None,2026-06-15 13:39:29.394476+00:00
48618,TRX002813,TRXD006366,CUST006714,EMP000756,THE GREEK PIZZA,CLASSIC,XXL,291195.0,260738.0,1,2025-02-16,18:15:02,18:29:26,0,None,2026-06-15 13:39:29.394476+00:00

## <b>C.2. <span style='color:#0B2F9F'><code>Mengubah String menjadi Tanggal</code></span></b>

Adakalanya format tanggal yang disimpan pada database tidak disimpan dalam format date yang baku (<a href="https://www.iso.org/iso-8601-date-and-time-format.html">ISO 8601</a>) sehingga perlu penyesuaian. Gunakan : <br><br>
<table border="1">
    <thead>
        <tr>
            <th>Fungsi</th>
            <th>Deskripsi</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td><code>PARSE_DATE(format, string_expression)</code></td>
            <td>Mengubah String menjadi Date</td>
        </tr>
        <tr>
            <td><code>FORMAT_DATE(format, date_expression)</code></td>
            <td>Mengubah Date menjadi String</td>
        </tr>
    </tbody>
</table><br>

Untuk detail format tanggal akses link berikut https://docs.cloud.google.com/bigquery/docs/reference/standard-sql/format-elements

#### <i><b><span style='color:#55679C'>Quest</span> : Tampilkan order_date dan order_date_iso pada tabel tbl_all_transaction. Dimana kolom order_date merupakan kolom dengan data asli dan order_date_iso merupakan kolom order_date yang diubah formatnya menjadi YYYY-MM-DD sesuai ISO 8601!</b></i><br>

In [27]:
%%bigquery --project {project_id} --verbose

SELECT
  order_date,
  PARSE_DATE('%m/%d/%Y', order_date) AS order_date_iso
FROM dqpizza.transaction_order

Executing query with job ID: 43966e0d-0ca6-4e4d-9526-f6c540f53a6f
Query executing: 0.68s
Job ID 43966e0d-0ca6-4e4d-9526-f6c540f53a6f successfully executed

Query is running:   0%|          |

Downloading:   0%|          |

       order_date order_date_iso
0      01/01/2025     2025-01-01
1      01/01/2025     2025-01-01
2      01/01/2025     2025-01-01
3      01/02/2025     2025-01-02
4      01/02/2025     2025-01-02
...           ...            ...
21345  06/12/2025     2025-06-12
21346  07/05/2025     2025-07-05
21347  07/06/2025     2025-07-06
21348  07/21/2025     2025-07-21
21349  11/30/2025     2025-11-30

[21350 rows x 2 columns]

In [ ]:
%%bigquery --project {project_id} --verbose

SELECT
  order_date,
  FORMAT_DATE('%Y-%m-%d', order_date) AS order_date_iso
FROM dqpizza.tbl_all_transaction

Executing query with job ID: 61b5b5dc-d646-461b-a540-4e21ed09862b
Query executing: 2.21s
Job ID 61b5b5dc-d646-461b-a540-4e21ed09862b successfully executed

Query is running:   0%|          |

Downloading:   0%|          |

       order_date order_date_iso
0      01/12/2024     2024-01-12
1      03/10/2024     2024-03-10
2      02/01/2024     2024-02-01
3      10/22/2024     2024-10-22
4      12/03/2024     2024-12-03
...           ...            ...
48618  11/27/2024     2024-11-27
48619  11/27/2024     2024-11-27
48620  11/27/2024     2024-11-27
48621  11/27/2024     2024-11-27
48622  11/27/2024     2024-11-27

[48623 rows x 2 columns]

## <b>C.3. <span style='color:#0B2F9F'><code>Menambahkan atau Mengurangi Tanggal</code></span></b>

<table border="1">
    <thead>
        <tr>
            <th>Fungsi</th>
            <th>Deskripsi</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td><code>DATE_ADD(tanggal, INTERVAL jumlah_penambahan satuan_waktu)</code></td>
            <td>Menambahkan Tanggal pada Interval Tertentu</td>
        </tr>
        <tr>
            <td><code>DATE_SUB(tanggal, INTERVAL jumlah_penambahan satuan_waktu)</code></td>
            <td>Mengurangi Tanggal pada Interval Tertentu</td>
        </tr>
        <tr>
            <td><code>DATE_DIFF(end_date, start_date, date_part)</code></td>
            <td>Menghitung selisih tanggal</td>
        </tr>
    </tbody>
</table><br>

Sebagai contoh misalkan hari ini tanggal 30 Oktober 2025. Ingin diperoleh tanggal tepat 3 bulan yang lalu maka dapat digunakan sintaks `DATE_SUB(DATE('2025-10-30'), INTERVAL 3 MONTH)` maka akan diperoleh tanggal 30 Juli 2025.

#### <i><b><span style='color:#55679C'>Quest</span> : Manajer ingin melakukan analisa demografi customer, pada tabel customers tampilkan customer_id, customer_name, gender dan age-nya per hari ini!</b></i><br>

In [42]:
%%bigquery --project {project_id} --verbose

SELECT
  customer_id,
  customer_name,
  gender,
  birth_date,
  DATE_DIFF(CURRENT_DATE(), PARSE_DATE('%Y-%m-%d', birth_date), YEAR) AS age,
  DATE_DIFF(CURRENT_DATE(), CAST(birth_date AS DATE), YEAR) AS ages
FROM dqpizza.master_customer

Executing query with job ID: b3302d53-16ac-40b2-af86-aa2e30801025
Query executing: 0.62s
Job ID b3302d53-16ac-40b2-af86-aa2e30801025 successfully executed

Query is running:   0%|          |

Downloading:   0%|          |

    customer_id           customer_name gender  birth_date  age  ages
0    CUST007150     Salsabila Purnawati      F  1990-09-17   36    36
1    CUST003319      Cornelia Wijayanti      F  1997-03-05   29    29
2    CUST007254            Elma Maryati      F  1984-03-25   42    42
3    CUST004392            Najwa Natsir      F  1980-05-25   46    46
4    CUST005127           Hani Palastri      F  2003-02-10   23    23
..          ...                     ...    ...         ...  ...   ...
132  CUST009056           Gada Winarsih      M  2000-12-07   26    26
133  CUST009366        Mulyanto Suryono      M  2001-02-17   25    25
134  CUST009522  Cakrawangsa Hutagalung      M  1989-03-25   37    37
135  CUST009700       Asirwanda Hidayat      M  1991-01-15   35    35
136  CUST009875            Wadi Jailani      M  1996-02-28   30    30

[137 rows x 6 columns]

## <b>C.5. <span style='color:#0B2F9F'><code>Mendapatkan Bagian pada Tanggal</code></span></b>

Mengambil bagian tertentu dari tipe data tanggal, waktu, atau timestamp terkadang sangat perlu dilakukan untuk analisa data. Jika ingin didapatkan elemen tertentu, seperti tahun, bulan, hari, atau jam, dari nilai tanggal atau waktu gunakan fungsi berikut<br><br>

<code>EXTRACT(bagian FROM tanggal)</code>
<br><br>

Bagian yang bisa diambil pada tanggal diantaranya adalah
<table border="1">
    <thead>
        <tr>
            <th>Bagian</th>
            <th>Deskripsi</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td><code>YEAR</code></td>
            <td>Mendapatkan Tahun pada Tanggal</td>
        </tr>
        <tr>
            <td><code>MONTH</code></td>
            <td>Mendapatkan Bulan pada Tanggal</td>
        </tr>
        <tr>
            <td><code>DAY</code></td>
            <td>Mendapatkan Hari (1-31) pada Tanggal</td>
        </tr>
        <tr>
            <td><code>WEEK</code></td>
            <td>Mendapatkan Minggu ke- pada Tanggal</td>
        </tr>
         <tr>
            <td><code>QUARTER</code></td>
            <td>Mendapatkan Kuartal pada Tanggal</td>
        </tr>
        <tr>
            <td><code>HOUR</code></td>
            <td>Mendapatkan Jam pada Waktu</td>
        </tr>
        <tr>
            <td><code>MINUTE</code></td>
            <td>Mendapatkan Menit pada Waktu</td>
        </tr>
        <tr>
            <td><code>SECOND</code></td>
            <td>Mendapatkan Detik pada Waktu</td>
        </tr>
    </tbody>
</table>
<br>

Namun jika menginginkan bagian yang lebih detail seperti Nama Bulan atau Nama Hari pada tanggal tertentu atau menampilkan format tanggal sesuai dengan keinginan dapat menggunakan sintaks `FORMAT_DATE(format_element, tanggal)`. <br><br>

<table border="1">
    <thead>
        <tr>
            <th>Sintaks</th>
            <th>Deskripsi</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td><code>FORMAT_DATE('%A', tanggal)</code></td>
            <td>Mendapatkan Nama Hari pada Tanggal Tertentu</td>
        </tr>
        <tr>
            <td><code>FORMAT_DATE('%B', tanggal)</code></td>
            <td>Mendapatkan Nama Bulan pada Tanggal Tertentu</td>
        </tr>
    </tbody>
</table>
<br>

Detail format_element dapat diakses dilaman <a href="https://cloud.google.com/bigquery/docs/reference/standard-sql/format-elements#format_elements_date_time"> berikut</a>.

#### <i><b><span style='color:#55679C'>Quest</span> : Hitung total transaksi dan total pendapatan yang diperoleh tiap bulan pada tahun 2025 di DQPizza! </b></i><br>

In [48]:
%%bigquery --project {project_id} --verbose

SELECT
  EXTRACT (MONTH FROM order_date) AS month,
  EXTRACT (YEAR FROM order_date) AS year,
  FORMAT_DATE('%Y-%m', order_date) AS year_month,
  COUNT(DISTINCT order_id) AS total_transaction,
  SUM(pizza_price * quantity) AS total_revenue

FROM dqpizza.tbl_all_transaction
WHERE order_date BETWEEN '2025-01-01' AND '2025-12-31'
GROUP BY
  month,
  year,
  year_month
ORDER BY year_month

Executing query with job ID: 096b37f6-385d-45e1-bc15-56849cd215c1
Query executing: 0.76s
Job ID 096b37f6-385d-45e1-bc15-56849cd215c1 successfully executed

Query is running:   0%|          |

Downloading:   0%|          |

    month  year year_month  total_transaction  total_revenue
0       1  2025    2025-01               1845    565325730.0
1       2  2025    2025-02               1685    527792760.0
2       3  2025    2025-03               1840    570216510.0
3       4  2025    2025-04               1795    556243605.0
4       5  2025    2025-05               1853    578362275.0
5       6  2025    2025-06               1773    552664620.0
6       7  2025    2025-07               1935    587718990.0
7       8  2025    2025-08               1841    553053825.0
8       9  2025    2025-09               1661    520073055.0
9      10  2025    2025-10               1646    518623560.0
10     11  2025    2025-11               1792    570202335.0
11     12  2025    2025-12               1680    524224710.0

# <b>D. <span style='color:#0B2F9F'><code>SUB-QUERY</code></span></b>
Subquery adalah sebuah query (pernyataan SQL) yang terletak di dalam query lain. Subquery dapat digunakan untuk mengambil data yang kemudian akan digunakan oleh query utama.<br><br>

#### <i><b><span style='color:#55679C'>Quest</span> : Pada tabel customers, hitung rata-rata umur customer dan bulatkan ke dua tempat desimal!</b></i>

In [51]:
%%bigquery --project {project_id} --verbose

SELECT ROUND(AVG(DATE_DIFF(CURRENT_DATE(), CAST(birth_date AS DATE), YEAR)), 2) AS avg_age
FROM dqpizza.master_customer

Executing query with job ID: d6da5add-4975-4983-a024-8b23a824e9c3
Query executing: 0.67s
Job ID d6da5add-4975-4983-a024-8b23a824e9c3 successfully executed

Query is running:   0%|          |

Downloading:   0%|          |

   avg_age
0    35.04

#### <i><b><span style='color:#55679C'>Quest</span> : Pada tabel customers, tampilkan customer_id, age dan gendernya dimana umur customer tersebut lebih dari rata-rata umur customer secara keseluruhan!</b></i>

In [53]:
%%bigquery --project {project_id} --verbose

SELECT
  customer_id,
  customer_name,
  gender,
  DATE_DIFF(CURRENT_DATE(), CAST(birth_date AS DATE), YEAR) AS age
FROM dqpizza.master_customer
WHERE DATE_DIFF(CURRENT_DATE(), CAST(birth_date AS DATE), YEAR) > (
  SELECT ROUND(AVG(DATE_DIFF(CURRENT_DATE(), CAST(birth_date AS DATE), YEAR)), 2) AS avg_age
  FROM dqpizza.master_customer
)

Executing query with job ID: 7f971528-5db4-4fa0-9747-ec216d5f96a9
Query executing: 2.25s
Job ID 7f971528-5db4-4fa0-9747-ec216d5f96a9 successfully executed

Query is running:   0%|          |

Downloading:   0%|          |

   customer_id           customer_name gender  age
0   CUST007150     Salsabila Purnawati      F   36
1   CUST007254            Elma Maryati      F   42
2   CUST004392            Najwa Natsir      F   46
3   CUST004504          Septi Latupono      F   44
4   CUST001597       Aisyah Laksmiwati      F   36
..         ...                     ...    ...  ...
64  CUST002244           Embuh Jailani      M   46
65  CUST003103         Asmuni Hutasoit      M   38
66  CUST008804       Arsipatra Prabowo      M   38
67  CUST008854           Nrima Damanik      M   39
68  CUST009522  Cakrawangsa Hutagalung      M   37

[69 rows x 4 columns]

#### <i><b><span style='color:#55679C'>Quest</span> : Pada tabel customers, tampilkan customer_id, age dan gendernya dimana gender Laki dan Perempuan keseluruhan!</b></i>

In [54]:
%%bigquery --project {project_id} --verbose

SELECT
  gender,
  min (age) AS min_age,
  max (age) AS max_age,
  avg (age) AS avg_age

FROM (
  SELECT
    customer_id,
    customer_name,
    gender,
    DATE_DIFF(CURRENT_DATE(), CAST(birth_date AS DATE), YEAR) AS age
  FROM dqpizza.master_customer
)

GROUP BY gender

Executing query with job ID: 4a2169bb-dc09-45ac-8880-6fd0551cd9f5
Query executing: 0.69s
Job ID 4a2169bb-dc09-45ac-8880-6fd0551cd9f5 successfully executed

Query is running:   0%|          |

Downloading:   0%|          |

  gender  min_age  max_age    avg_age
0      F       19       52  36.928571
1      M       19       52  33.059701

# <b>E. <span style='color:#0B2F9F'><code>Common Table Expression (CTE)</code></span></b>
CTE, atau Common Table Expression, adalah fitur dalam SQL yang memungkinkan Anda untuk mendefinisikan sebuah query sementara yang dapat digunakan dalam query lain. CTE membantu dalam membuat query lebih mudah dibaca dan dipelihara, serta memungkinkan penggunaan rekursi dalam query.

<img src="https://learnsql.com/blog/sql-common-table-expression-guide/cte_syntax_example.webp" width="50%">

#### <i><b><span style='color:#55679C'>Quest</span> : Siapakah customer yang paling banyak spending money di DQPizza?</b></i>

In [61]:
%%bigquery --project {project_id} --verbose

WITH customer_spending AS (
  SELECT
    customer_id,
    SUM(pizza_price * quantity) AS total_spending
  FROM dqpizza.tbl_all_transaction
  GROUP BY customer_id
)

SELECT * FROM customer_spending
WHERE total_spending = (SELECT MAX(total_spending) FROM customer_spending)

Executing query with job ID: de804ee2-9bd4-4f79-bede-b6473be25ec0
Query executing: 0.65s
Job ID de804ee2-9bd4-4f79-bede-b6473be25ec0 successfully executed

Query is running:   0%|          |

Downloading:   0%|          |

  customer_id  total_spending
0  CUST006333     237372120.0

Data Source : <i>https://mavenanalytics.io/challenges/maven-pizza-challenge</i> (dengan modifikasi)


---

<a href="https://dqlab.id/"><img src="https://dqlab.id/files/dqlab/cache/87e30118ebba5ec7d96f6ea8c9dcc10b_x_118_X_55.png" align="left" /></a>