<a href="https://colab.research.google.com/github/refianP13/Data-Analyst/blob/main/Copy_of_DQLab_Join_Method.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# <b><span style='color:#0B2F9F'>Pengantar</span></b>

Dalam pengelolaan data, sering kali informasi yang dibutuhkan tersebar di beberapa tabel yang saling berhubungan. Untuk memperoleh gambaran yang utuh, diperlukan cara untuk menggabungkan data-data tersebut secara tepat dan efisien. Konsep JOIN dalam SQL memungkinkan penggabungan data dari dua atau lebih tabel berdasarkan kolom yang memiliki relasi tertentu, sehingga informasi yang terpisah dapat ditampilkan dalam satu hasil query yang terpadu. Dengan memahami dan menerapkan berbagai jenis JOIN—seperti INNER JOIN, LEFT JOIN, RIGHT JOIN, dan FULL JOIN—seseorang dapat mengintegrasikan data dengan lebih fleksibel, memperkaya hasil analisis, serta meningkatkan ketepatan dalam pengambilan keputusan berbasis data.

# <b><span style='color:#0B2F9F'>Entity Relationalship Diagram</span></b>

Dalam sistem pemesanan pizza, terdapat beberapa entitas utama yang saling berhubungan. ERD (Entity Relationship Diagram) membantu menggambarkan hubungan antar tabel tersebut agar struktur data lebih mudah dipahami dan dikelola.

<img src="https://raw.githubusercontent.com/bachtiyarwork/Image/main/ERD%20-%20Pizza.jpg" width="60%">

Antar tabel bisa saling berelasi sesuai dengan peran dan hubungan logisnya melalui sebuah 'kunci'

# <b><span style='color:#0B2F9F'>Set up</span></b>

Dibutuhkan proses autentikasi dari Google Colab ke Google Big Query. Ikuti langkah berikut https://drive.google.com/file/d/1gW8alZ_PrvcrsieqWCHOR4ssLI_25BRc/view untuk detail step-by-step nya

In [ ]:
# Import library yang dibutuhkan
from google.colab import auth, data_table
from google.cloud import bigquery
from pandas_gbq import to_gbq
import pandas as pd
pd.set_option('display.float_format', '{:.2f}'.format)

# Proses autentikasi akun
auth.authenticate_user()
print('Authenticated')

Authenticated

In [ ]:
# Buat BigQuery client
project_id = 'dqlabs-project'
client = bigquery.Client(project = project_id)

# <b>A. <span style='color:#0B2F9F'><code>PREFIX</code></span></b>
Prefix merupakan penggunaan awalan pada nama tabel untuk memberikan informasi tambahan atau untuk mengelompokkan objek-objek tertentu. Sebagai contoh perhatikan gambar berikut : <br>

<img src="https://raw.githubusercontent.com/bachtiyarma/Material/refs/heads/main/Image/Materi-SQL/SQL%20-%20Prefix.png" width="50%">

<br>

Nama tabel dimisalkan (diberi alias) sebagai tbl, lalu untuk mengakses kolom pada tabel tersebut bisa diberi prefix tbl.kolom1 dan seterusnya

#### <i><b><span style='color:#55679C'>Quest</span> : Pada tabel customers, ambil kolom customer_id, name dan gender namun gunakan alias 'c' pada nama tabel dan sematkan prefixnya saat mengakses kolom!</b></i>

In [ ]:
%%bigquery --project {project_id} --verbose

SELECT c.customer_id, c.customer_name, c.gender
FROM `dqpizza.master_customer` AS c

Executing query with job ID: 3f010e1e-f27f-4453-a719-d210c12db309
Query executing: 0.75s
Job ID 3f010e1e-f27f-4453-a719-d210c12db309 successfully executed

Query is running:   0%|          |

Downloading:   0%|          |

    customer_id           customer_name gender
0    CUST007150     Salsabila Purnawati      F
1    CUST003319      Cornelia Wijayanti      F
2    CUST007254            Elma Maryati      F
3    CUST004392            Najwa Natsir      F
4    CUST005127           Hani Palastri      F
..          ...                     ...    ...
132  CUST009056           Gada Winarsih      M
133  CUST009366        Mulyanto Suryono      M
134  CUST009522  Cakrawangsa Hutagalung      M
135  CUST009700       Asirwanda Hidayat      M
136  CUST009875            Wadi Jailani      M

[137 rows x 3 columns]

# <b>B. <span style='color:#0B2F9F'><code>JOIN</code></span></b>

Data biasanya disimpan di berbagai tabel atau sistem yang berbeda pada RDBMS (Relational Database Management System). JOIN memungkinkan pengguna untuk menggabungkan data dari berbagai sumber untuk mendapatkan gambaran yang lebih lengkap. Memahami query JOIN memungkinkan seorang pengguna untuk mengintegrasikan dan menganalisis data secara efektif, sehingga dapat meningkatkan kualitas analisis dan mendukung pengambilan keputusan berbasis data.

Operasi JOIN standar dapat dilakukan jika terdapat kunci pada tiap tabel yang saling terhubung. Operasi join dasar yang paling umum digunakan ada 4 yakni :
<ul>
    <li><b>LEFT JOIN</b></li>
    LEFT JOIN adalah jenis operasi penggabungan baris dari dua tabel, tetapi hanya mengembalikan semua baris dari tabel kiri (tabel pertama) dan baris yang cocok dari tabel kanan (tabel kedua). Jika tidak ada kecocokan di tabel kanan, maka nilai-nilai untuk kolom dari tabel kanan akan diisi dengan NULL.<br><br>
    <img src="https://learn.microsoft.com/en-us/power-query/media/merge-queries-left-outer/left-outer-join-operation.png" width="40%">
    <br><br>
    <li><b>RIGHT JOIN</b></li>
    RIGHT JOIN adalah jenis operasi penggabungan baris dari dua tabel, tetapi hanya mengembalikan semua baris dari tabel kanan (tabel kedua) dan baris yang cocok dari tabel kiri (tabel pertama). Jika tidak ada kecocokan di tabel kiri, maka nilai-nilai untuk kolom dari tabel kiri akan diisi dengan NULL.<br><br>
    <img src="https://learn.microsoft.com/en-us/power-query/media/merge-queries-right-outer/right-outer-join-operation.png" width="40%">
    <br><br>
    <li><b>INNER JOIN</b></li>
    INNER JOIN adalah jenis operasi penggabungan yang hanya mengembalikan baris yang memiliki kecocokan di kedua tabel berdasarkan kriteria tertentu.<br><br>
    <img src="https://learn.microsoft.com/en-us/power-query/media/merge-queries-inner/inner-join-operation.png" width="40%">
    <br><br>
     <li><b>FULL JOIN</b></li>
    FULL JOIN adalah jenis operasi penggabungan semua baris dari kedua tabel, baik yang memiliki kecocokan maupun yang tidak. Dengan demikian, hasilnya akan mencakup semua data dari tabel kiri dan tabel kanan.<br><br>
    <img src="https://learn.microsoft.com/en-us/power-query/media/merge-queries-full-outer/full-outer-join-operation.png" width="40%">
    <br><br>
</ul>

#### <i><b><span style='color:#55679C'>Quest : </span>Untuk mengetahui informasi mengenai banyak transaksi tiap customer (yang pernah bertransaksi saja); tampilkan customer_id, nama, gender, banyak transaksi yang pernah dilakukan urutkan berdasarkan transaksi terbanyak!

In [13]:
%%bigquery --project {project_id} --verbose

SELECT c.customer_id, c.customer_name, c.gender, COUNT(DISTINCT o.order_id) AS total_order
FROM `dqpizza.master_customer` AS c
INNER JOIN `dqpizza.transaction_order` AS o ON c.customer_id = o.customer_id
GROUP BY c.customer_id, c.customer_name, c.gender
ORDER BY total_order DESC

Executing query with job ID: 6a7a8dec-d822-4673-951a-738efcfcdeae
Query executing: 0.63s
Job ID 6a7a8dec-d822-4673-951a-738efcfcdeae successfully executed

Query is running:   0%|          |

Downloading:   0%|          |

    customer_id       customer_name gender  total_order
0    CUST006333  Darijan Nainggolan      M          741
1    CUST009381          Ani Habibi      F          702
2    CUST007656     Kusuma Prastuti      M          614
3    CUST003549      Laras Palastri      F          580
4    CUST009740       Mujur Jailani      M          523
..          ...                 ...    ...          ...
115  CUST002478       Alika Nugroho      F           17
116  CUST004307       Jelita Waluyo      F           17
117  CUST001029      Alika Dongoran      F           14
118  CUST003871     Paulin Najmudin      F           13
119  CUST006892     Emong Manullang      M           12

[120 rows x 4 columns]

#### <i><b><span style='color:#55679C'>Quest : </span>Kita perlu approch customer terdaftar namun belum pernah bertransaksi (belum pernah membeli pizza) di DQPizza, tampilkan identitas lengkap customer sesuai kriteria tersebut!

In [12]:
%%bigquery --project {project_id} --verbose

SELECT c.customer_id, c.customer_name, c.gender, c.birth_date, c.phone_number, c.email
FROM `dqpizza.master_customer` AS c
LEFT JOIN `dqpizza.transaction_order` AS o ON c.customer_id = o.customer_id
WHERE o.order_id IS NULL

Executing query with job ID: ec3fbd1b-8aff-4148-aa47-78348ef2635e
Query executing: 1.03s
Job ID ec3fbd1b-8aff-4148-aa47-78348ef2635e successfully executed

Query is running:   0%|          |

Downloading:   0%|          |

,customer_id,customer_name,gender,birth_date,phone_number,email
0,CUST008842,Ani Purnawati,F,1998-12-13,+62 (0295) 880 4741,ani.purnawati@hotmail.com
1,CUST008966,Rahmi Padmasari,F,1980-11-06,+62 (027) 871 2336,rahmi.padmasari@gmail.com
2,CUST009022,Raisa Puspasari,F,1986-09-30,+62 (0743) 448 8286,raisa.puspasari@yahoo.com
3,CUST009070,Shania Tampubolon,F,2003-04-19,+62 (025) 592 9792,shania.tampubolon@gmail.com
4,CUST009403,Ifa Halimah,F,1983-12-24,+62 (91) 114-8861,ifa.halimah@hotmail.com
5,CUST009448,Cinthia Mayasari,F,1994-07-03,+62 (304) 769-4866,cinthia.mayasari@hotmail.com
6,CUST009620,Ratna Pradipta,F,1987-11-14,+62 (149) 212-4956,ratna.pradipta@yahoo.com
7,CUST009942,Jessica Wulandari,F,2005-08-29,080 239 5170,jessica.wulandari@yahoo.com
8,CUST009990,Rina Uyainah,F,1984-08-05,(0829) 610 9735,rina.uyainah@yahoo.com
9,CUST008804,Arsipatra Prabowo,M,1988-04-30,+62 (031) 219-5383,arsipatra.prabowo@gmail.com
10,CUST008854,Nrima Damanik,M,1987-03-19,+62 (503) 118-7949,nrima.damanik@yahoo.com
11,CUST008990,Rangga Nababan,M,2007-01-04,+62-0992-496-9678,rangga.nababan@gmail.com
12,CUST009056,Gada Winarsih,M,2000-12-07,0809259635,gada.winarsih@hotmail.com
13,CUST009366,Mulyanto Suryono,M,2001-02-17,+62-0885-877-0893,mulyanto.suryono@yahoo.com
14,CUST009522,Cakrawangsa Hutagalung,M,1989-03-25,+62 (39) 581-0404,cakrawangsa.hutagalung@gmail.com
15,CUST009700,Asirwanda Hidayat,M,1991-01-15,0837121476,asirwanda.hidayat@hotmail.com
16,CUST009875,Wadi Jailani,M,1996-02-28,088 915 7132,wadi.jailani@yahoo.com

#### <i><b><span style='color:#55679C'>Quest : </span>Kategori pizza apa yang menyumbang pendapatan paling besar di DQPizza pada tahun 2024?

In [48]:
%%bigquery --project {project_id} --verbose

SELECT DISTINCT
  UPPER(mpt.category) AS pizza_category,
  COUNT(DISTINCT t.order_id) AS total_order,
  SUM(td.quantity) AS total_quantity,
  SUM(SAFE_CAST(REPLACE(mp.price, 'IDR', '') AS FLOAT64) * td.quantity) AS total_revenue
FROM dqpizza.transaction_order AS t
INNER JOIN dqpizza.transaction_order_detail AS td ON t.order_id = td.order_id
INNER JOIN dqpizza.master_pizza AS mp ON td.pizza_id = mp.pizza_id
INNER JOIN dqpizza.master_pizza_type AS mpt ON mp.pizza_type_id = mpt.pizza_type_id
WHERE EXTRACT(YEAR FROM PARSE_DATE('%m/%d/%Y', t.order_date)) = 2024
GROUP BY UPPER(mpt.category)
ORDER BY total_revenue DESC

Executing query with job ID: 49960050-e083-4dcc-9c79-e3b441b715be
Query executing: 0.70s
Job ID 49960050-e083-4dcc-9c79-e3b441b715be successfully executed

Query is running:   0%|          |

Downloading:   0%|          |

  pizza_category  total_order  total_quantity  total_revenue
0        CLASSIC        10859           14890  1782644760.00
1        SUPREME         9085           11987  1686395700.00
2        CHICKEN         8536           11050  1586947950.00
3         VEGGIE         8941           11650  1569038040.00

In [ ]:
%%bigquery --project {project_id} --verbose

  pizza_category  total_order  total_quantity  total_revenue
0        CLASSIC        10859           14890  1782644760.00
1        SUPREME         9085           11987  1686395700.00
2        CHICKEN         8536           11050  1586947950.00
3         VEGGIE         8941           11650  1569038040.00

---

# **Mari Kita Mulai Petualangan Besarnya!**

Setelah mempelajari banyak hal mengenai query, kini saatnya kamu membantu kami untuk menganalisa lebih dalam data yang kami miliki.

<img src="https://raw.githubusercontent.com/bachtiyarwork/Image/main/DQPizza%20-%20Aksara.png" width="30%">

Untuk mempermudah pekerjaanmu nantinya, mari kita membuat sebuah tabel yang akan kita beri nama `tbl_detail_transaction`. Tabel ini akan memuat seluruh detail transaksi pizza dengan **mengintegrasikan seluruh tabel** yang dimiliki dan **memastikan data yang bersih** agar data transaksi dapat dianalisis secara lebih komprehensif dan efisien dalam satu sumber data terpusat.

Ikuti *step-by-step* berikut ya!

## **Bagian 1** - `transaction_order`

Ambil kolom *order_id, customer_id, order_maker_id, order_date, order_time, completion_time, duration_in_minutes, is_complain* dan *complain detail* pada table **transaction_order** dengan ketentuan :
1. Pastikan kolom order_date memiliki format 'YYYY-MM-DD', bertipe data DATE dan pastikan nama kolom aliasnya tetap order_date
2. Pastikan kolom order_time dan completion_time memiliki format 'HH:MM:SS', bertipe data TIME lalu pastikan nama kolom aliasnya tetap *order_time* dan *completion_time*
3. Untuk kolom baru *duration_in_minutes* merupakan kolom yang menyatakan lamanya pizza tersaji dari saat pesanan diinput ke sistem dengan kata lain selisih dalam satuan menit antara completion_time dengan order_time
4. Ambil hanya data yang 'ID Pesanannya' nya tidak kosong untuk menjaga validitas transaksi
5. Tampilkan hasilnya sesuai expected output berikut<br><br><img src="https://raw.githubusercontent.com/bachtiyarwork/Image/main/DQPizza%20-%20Project%20Bagian%201.png" width="80%">

In [54]:
%%bigquery --project {project_id} --verbose

SELECT
  order_id,
  customer_id,
  order_maker_id,
  PARSE_DATE('%m/%d/%Y', order_date) AS order_date,
  PARSE_TIME('%H:%M:%S', order_time) AS order_time,
  PARSE_TIME('%H:%M:%S', completion_time) AS completion_time,
  TIME_DIFF(PARSE_TIME('%H:%M:%S', completion_time), PARSE_TIME('%H:%M:%S', order_time), MINUTE) AS duration_in_minutes,
  is_complain,
  complain_detail
FROM `dqpizza.transaction_order`
WHERE order_id IS NOT NULL

Executing query with job ID: c8d40a31-5cfb-430b-8ad6-0b86712f61fb
Query executing: 1.41s
Job ID c8d40a31-5cfb-430b-8ad6-0b86712f61fb successfully executed

Query is running:   0%|          |

Downloading:   0%|          |

,order_id,customer_id,order_maker_id,order_date,order_time,completion_time,duration_in_minutes,is_complain,complain_detail
0,TRX000026,CUST006333,EMP000208,2025-01-01,14:54:26,15:23:02,29,0,None
1,TRX000037,CUST003319,EMP000208,2025-01-01,16:56:09,17:18:48,22,0,None
2,TRX000057,CUST008422,EMP000208,2025-01-01,19:10:51,19:30:38,20,0,None
3,TRX000077,CUST001979,EMP000208,2025-01-02,12:22:46,12:41:29,19,0,None
4,TRX000087,CUST004837,EMP000208,2025-01-02,14:01:02,14:29:46,28,0,None
...,...,...,...,...,...,...,...,...,...
21345,TRX009714,CUST004609,EMP000756,2025-06-12,15:32:54,15:52:27,20,1,Wrong pizza size
21346,TRX011127,CUST003549,EMP000756,2025-07-05,12:49:09,13:03:28,14,1,Wrong pizza size
21347,TRX011178,CUST008535,EMP000756,2025-07-06,13:09:22,13:28:47,19,1,Wrong pizza size
21348,TRX012098,CUST001979,EMP000756,2025-07-21,18:11:15,18:33:56,22,1,Wrong pizza size
21349,TRX019645,CUST001120,EMP000756,2025-11-30,17:07:35,17:34:36,27,1,Wrong pizza size

## **Bagian 2** - `transaction_order_detail`

Ambil kolom *order_details_id, order_id, pizza_id,* dan *quantity* pada tabel **transaction_order_detail** dengan ketentuan :
1. Ambil hanya data yang 'ID Pesanan' dan 'ID Detail Pesanan'-nya tidak kosong untuk menjaga validitas transaksi
2. Tampilkan hasilnya sesuai expected output berikut<br><br><img src="https://raw.githubusercontent.com/bachtiyarwork/Image/main/DQPizza%20-%20Project%20Bagian%202.png" width="45%">

In [55]:
%%bigquery --project {project_id} --verbose

SELECT
  order_details_id,
  order_id,
  pizza_id,
  quantity
FROM `dqpizza.transaction_order_detail`
WHERE order_id IS NOT NULL AND order_details_id IS NOT NULL

Executing query with job ID: 848daacc-3bd9-4c8d-9c7e-11eef0108e3b
Query executing: 1.67s
Job ID 848daacc-3bd9-4c8d-9c7e-11eef0108e3b successfully executed

Query is running:   0%|          |

Downloading:   0%|          |

      order_details_id   order_id              pizza_id  quantity
0           TRXD000019  TRX000009     PIZZA_ITAL_SUPR_S         1
1           TRXD000020  TRX000009      PIZZA_MEXICANA_S         1
2           TRXD000074  TRX000028   PIZZA_CKN_ALFREDO_S         1
3           TRXD000080  TRX000032  PIZZA_GREEN_GARDEN_L         1
4           TRXD000171  TRX000075     PIZZA_ITAL_SUPR_S         1
...                ...        ...                   ...       ...
48614       TRXD048406  TRX021251    PIZZA_VEGGIE_VEG_S         2
48615       TRXD048493  TRX021296    PIZZA_VEGGIE_VEG_S         1
48616       TRXD048500  TRX021298    PIZZA_VEGGIE_VEG_S         1
48617       TRXD048503  TRX021299    PIZZA_VEGGIE_VEG_S         1
48618       TRXD048553  TRX021319    PIZZA_VEGGIE_VEG_S         1

[48619 rows x 4 columns]

## **Bagian 3** - `master_pizza`

Ambil kolom *pizza_id, pizza_type_id, size, price* dan *production_cost* pada tabel **master_pizza** dengan ketentuan :
1. Tampilkan kolom *size* dengan nama alias 'pizza_size'
2. Pastikan pada kolom price dan production_cost tidak mengandung *currency* atau simbol mata uang sehingga murni hanya angka saja, lalu pastikan tipe datanya menjadi FLOAT64 dan ubah penamaan alias kolomnya menjadi pizza_price dan pizza_production_cost
3. Karena tabel master_pizza adalah berjenis tabel master maka pastikan semua nilainya unik setiap barisnya
4. Ambil hanya data yang ID Pizza-nya tidak kosong
5. Tampilkan hasilnya sesuai expected output berikut<br><br><img src="https://raw.githubusercontent.com/bachtiyarwork/Image/main/DQPizza%20-%20Project%20Bagian%203.png" width="70%">

In [57]:
%%bigquery --project {project_id} --verbose

SELECT
  pizza_id,
  pizza_type_id,
  UPPER(size) AS pizza_size,
  CAST(REPLACE(price, 'IDR', '') AS FLOAT64) AS pizza_price,
  CAST(REPLACE(production_cost, 'IDR', '') AS FLOAT64) AS pizza_production_cost
FROM `dqpizza.master_pizza`
WHERE pizza_id IS NOT NULL

Executing query with job ID: 6c86b3fa-9cac-4b05-bb8a-572c7865eeac
Query executing: 0.85s
Job ID 6c86b3fa-9cac-4b05-bb8a-572c7865eeac successfully executed

Query is running:   0%|          |

Downloading:   0%|          |

,pizza_id,pizza_type_id,pizza_size,pizza_price,pizza_production_cost
0,PIZZA_PEPPERONI_L,PIZZA_TYPE_PEPPERONI,L,123525.00,96390.00
1,PIZZA_HAWAIIAN_L,PIZZA_TYPE_HAWAIIAN,L,133650.00,102951.00
2,PIZZA_PEP_MSH_PEP_L,PIZZA_TYPE_PEP_MSH_PEP,L,141750.00,111537.00
3,PIZZA_FOUR_CHEESE_L,PIZZA_TYPE_FOUR_CHEESE,L,145395.00,113724.00
4,PIZZA_FIVE_CHEESE_L,PIZZA_TYPE_FIVE_CHEESE,L,149850.00,124740.00
...,...,...,...,...,...
91,PIZZA_VEGGIE_VEG_S,PIZZA_TYPE_VEGGIE_VEG,S,97200.00,69093.00
92,PIZZA_CALABRESE_S,PIZZA_TYPE_CALABRESE,S,99225.00,81891.00
93,PIZZA_SICILIAN_S,PIZZA_TYPE_SICILIAN,S,99225.00,71685.00
94,PIZZA_THE_GREEK_XL,PIZZA_TYPE_THE_GREEK,XL,206550.00,157221.00
95,PIZZA_THE_GREEK_XXL,PIZZA_TYPE_THE_GREEK,XXL,291195.00,260738.00

## **Bagian 4** - `master_pizza_type`

Ambil kolom *pizza_type_id, name, category* dan *ingredients* pada tabel **master_pizza_type** dengan ketentuan :
1. Periksa nilai pada kolom name dan category. Yap! penulisannya tidak standar! Oleh karena itu ubah nilai kolom name dan category menjadi UPPERCASE lalu beri nama alias pizza_name dan pizza_category
3. Karena tabel master_pizza_type adalah berjenis tabel master maka pastikan semua nilainya unik setiap barisnya
4. Ambil hanya data yang 'ID Jenis Pizza'-nya tidak kosong
5. Tampilkan hasilnya sesuai expected output berikut <br><br><img src="https://raw.githubusercontent.com/bachtiyarwork/Image/main/DQPizza%20-%20Project%20Bagian%204.png" width="80%">

In [61]:
%%bigquery --project {project_id} --verbose

SELECT
  pizza_type_id,
  UPPER(name) AS pizza_name,
  UPPER(category) AS pizza_category,
  ingredients
FROM `dqpizza.master_pizza_type`
WHERE pizza_type_id IS NOT NULL
group by all

Executing query with job ID: da16b45d-9658-4aa5-afca-05ed081e11cd
Query executing: 0.37s
Job ID da16b45d-9658-4aa5-afca-05ed081e11cd successfully executed

Query is running:   0%|          |

Downloading:   0%|          |

,pizza_type_id,pizza_name,pizza_category,ingredients
0,PIZZA_TYPE_BBQ_CKN,THE BARBECUE CHICKEN PIZZA,CHICKEN,"Barbecued Chicken, Red Peppers, Green Peppers,..."
1,PIZZA_TYPE_CALI_CKN,THE CALIFORNIA CHICKEN PIZZA,CHICKEN,"Chicken, Artichoke, Spinach, Garlic, Jalapeno ..."
2,PIZZA_TYPE_SOUTHW_CKN,THE SOUTHWEST CHICKEN PIZZA,CHICKEN,"Chicken, Tomatoes, Red Peppers, Red Onions, Ja..."
3,PIZZA_TYPE_CLASSIC_DLX,THE CLASSIC DELUXE PIZZA,CLASSIC,"Pepperoni, Mushrooms, Red Onions, Red Peppers,..."
4,PIZZA_TYPE_HAWAIIAN,THE HAWAIIAN PIZZA,CLASSIC,"Sliced Ham, Pineapple, Mozzarella Cheese"
5,PIZZA_TYPE_PEPPERONI,THE PEPPERONI PIZZA,CLASSIC,"Mozzarella Cheese, Pepperoni"
6,PIZZA_TYPE_THE_GREEK,THE GREEK PIZZA,CLASSIC,"Kalamata Olives, Feta Cheese, Tomatoes, Garlic..."
7,PIZZA_TYPE_BIG_MEAT,THE BIG MEAT PIZZA,CLASSIC,"Bacon, Pepperoni, Italian Sausage, Chorizo Sau..."
8,PIZZA_TYPE_NAPOLITANA,THE NAPOLITANA PIZZA,CLASSIC,"Tomatoes, Anchovies, Green Olives, Red Onions,..."
9,PIZZA_TYPE_CALABRESE,THE CALABRESE PIZZA,SUPREME,"‘Nduja Salami, Pancetta, Tomatoes, Red Onions,..."
10,PIZZA_TYPE_PEPPR_SALAMI,THE PEPPER SALAMI PIZZA,SUPREME,"Genoa Salami, Capocollo, Pepperoni, Tomatoes, ..."
11,PIZZA_TYPE_SICILIAN,THE SICILIAN PIZZA,SUPREME,"Coarse Sicilian Salami, Tomatoes, Green Olives..."
12,PIZZA_TYPE_SPICY_ITAL,THE SPICY ITALIAN PIZZA,SUPREME,"Capocollo, Tomatoes, Goat Cheese, Artichokes, ..."
13,PIZZA_TYPE_SOPPRESSATA,THE SOPPRESSATA PIZZA,SUPREME,"Soppressata Salami, Fontina Cheese, Mozzarella..."
14,PIZZA_TYPE_ITAL_VEGGIE,THE ITALIAN VEGETABLES PIZZA,VEGGIE,"Eggplant, Artichokes, Tomatoes, Zucchini, Red ..."
15,PIZZA_TYPE_MEDITERRANEO,THE MEDITERRANEAN PIZZA,VEGGIE,"Spinach, Artichokes, Kalamata Olives, Sun-drie..."
16,PIZZA_TYPE_SPIN_PESTO,THE SPINACH PESTO PIZZA,VEGGIE,"Spinach, Artichokes, Tomatoes, Sun-dried Tomat..."
17,PIZZA_TYPE_SPINACH_FET,THE SPINACH AND FETA PIZZA,VEGGIE,"Spinach, Mushrooms, Red Onions, Feta Cheese, G..."
18,PIZZA_TYPE_CKN_ALFREDO,THE CHICKEN ALFREDO PIZZA,CHICKEN,"Chicken, Red Onions, Red Peppers, Mushrooms, A..."
19,PIZZA_TYPE_CKN_PESTO,THE CHICKEN PESTO PIZZA,CHICKEN,"Chicken, Tomatoes, Red Peppers, Spinach, Garli..."
20,PIZZA_TYPE_THAI_CKN,THE THAI CHICKEN PIZZA,CHICKEN,"Chicken, Pineapple, Tomatoes, Red Peppers, Tha..."
21,PIZZA_TYPE_ITAL_CPCLLO,THE ITALIAN CAPOCOLLO PIZZA,CLASSIC,"Capocollo, Red Peppers, Tomatoes, Goat Cheese,..."
22,PIZZA_TYPE_PEP_MSH_PEP,"THE PEPPERONI, MUSHROOM AND PEPPERS PIZZA",CLASSIC,"Pepperoni, Mushrooms, Green Peppers"
23,PIZZA_TYPE_BRIE_CARRE,THE BRIE CARRE PIZZA,SUPREME,"Brie Carre Cheese, Prosciutto, Caramelized Oni..."
24,PIZZA_TYPE_ITAL_SUPR,THE ITALIAN SUPREME PIZZA,SUPREME,"Calabrese Salami, Capocollo, Tomatoes, Red Oni..."
25,PIZZA_TYPE_PRSC_ARGLA,THE PROSCIUTTO AND ARUGULA PIZZA,SUPREME,"Prosciutto di San Daniele, Arugula, Mozzarella..."
26,PIZZA_TYPE_SPINACH_SUPR,THE SPINACH SUPREME PIZZA,SUPREME,"Spinach, Red Onions, Pepperoni, Tomatoes, Arti..."
27,PIZZA_TYPE_FIVE_CHEESE,THE FIVE CHEESE PIZZA,VEGGIE,"Mozzarella Cheese, Provolone Cheese, Smoked Go..."
28,PIZZA_TYPE_FOUR_CHEESE,THE FOUR CHEESE PIZZA,VEGGIE,"Ricotta Cheese, Gorgonzola Piccante Cheese, Mo..."
29,PIZZA_TYPE_GREEN_GARDEN,THE GREEN GARDEN PIZZA,VEGGIE,"Spinach, Mushrooms, Tomatoes, Green Olives, Fe..."
30,PIZZA_TYPE_MEXICANA,THE MEXICANA PIZZA,VEGGIE,"Tomatoes, Red Peppers, Jalapeno Peppers, Red O..."
31,PIZZA_TYPE_VEGGIE_VEG,THE VEGETABLES + VEGETABLES PIZZA,VEGGIE,"Mushrooms, Tomatoes, Red Peppers, Green Pepper..."

## **Bagian 5** - `master_customer`

Ambil kolom *customer_id, customer_name, gender, birth_date* dan *open_date* pada tabel **master_customer** dengan ketentuan :
1. Untuk kolom gender, ubah nama kolom aliasnya menjadi *customer_gender*
2. Asumsikan hari ini tepat pada tanggal 31 Desember 2025, hitung usia pelanggan dalam satuan tahun lalu beri nama kolom aliasnya menjadi *customer_age*
3. Dengan asumsi tanggal yang sama yakni 31 Desember 2025, hitung berapa lama customer berlangganan dalam satuan bulan dengan kata lain hitung selisih antara open_date dengan tanggal 31 Desember 2025 dalam satuan bulan lalu beri nama kolom aliasnya menjadi *customer_tenure_in_months*
4. Karena tabel master_customer adalah berjenis tabel master maka pastikan semua nilainya unik setiap barisnya
5. Ambil hanya data yang 'ID Jenis Pizza'-nya tidak kosong
6. Tampilkan hasilnya sesuai expected output berikut<br><br><img src="https://raw.githubusercontent.com/bachtiyarwork/Image/main/DQPizza%20-%20Project%20Bagian%205.png" width="60%">

In [87]:
%%bigquery --project {project_id} --verbose

SELECT DISTINCT
    customer_id,
    customer_name,
    gender AS customer_gender,
    -- Menghitung usia per 31 Desember 2025
    DATE_DIFF(DATE '2025-12-31', COALESCE(SAFE.PARSE_DATE('%Y-%m-%d', birth_date), SAFE.PARSE_DATE('%m/%d/%Y', birth_date), SAFE.PARSE_DATE('%Y/%m/%d', birth_date)), YEAR) AS customer_age,
    -- Menghitung masa berlangganan (tenure) dalam bulan per 31 Desember 2025
    DATE_DIFF(DATE '2025-12-31', COALESCE(SAFE.PARSE_DATE('%Y-%m-%d', open_date), SAFE.PARSE_DATE('%m/%d/%Y', open_date), SAFE.PARSE_DATE('%Y/%m/%d', open_date)), MONTH) AS customer_tenure_in_months
FROM
    dqpizza.master_customer
WHERE
    customer_id IS NOT NULL;

Executing query with job ID: 021733f5-1c81-43eb-aa0b-0e75f009e6a6
Query executing: 0.45s
Job ID 021733f5-1c81-43eb-aa0b-0e75f009e6a6 successfully executed

Query is running:   0%|          |

Downloading:   0%|          |

,customer_id,customer_name,customer_gender,customer_age,customer_tenure_in_months
0,CUST007150,Salsabila Purnawati,F,35,12
1,CUST003319,Cornelia Wijayanti,F,28,12
2,CUST007254,Elma Maryati,F,41,12
3,CUST004392,Najwa Natsir,F,45,12
4,CUST005127,Hani Palastri,F,22,12
...,...,...,...,...,...
132,CUST009056,Gada Winarsih,M,25,3
133,CUST009366,Mulyanto Suryono,M,24,3
134,CUST009522,Cakrawangsa Hutagalung,M,36,3
135,CUST009700,Asirwanda Hidayat,M,34,3
136,CUST009875,Wadi Jailani,M,29,3

Setelah semua bagian telah diatur kini saatnya melakukan proses integrasi data. Hmmm.. pada bagian ini kalian harus memastikan setiap tabel telah dibersihkan dan terhubung dengan tepat ya!

<img src="https://raw.githubusercontent.com/bachtiyarwork/Image/main/DQPizza%20-%20Aksara%20Confused.png" width="25%">

Aku percayakan hal ini pada kalian ...

## **Proses Integrasi**       
Untuk proses integrasi ini akan membutuhkan CTE dalam prosesnya, lengkapi query dibawah ini sesuai petunjuk berikutnya.

1. Pada CTE trx_order isikan query pada **Bagian 1** yang sudah dikonstruksikan sebelumnya
2. Pada CTE trx_order_detail isikan query pada **Bagian 2** yang sudah dikonstruksikan sebelumnya
3. Pada CTE mst_pizza isikan query pada **Bagian 3** yang sudah dikonstruksikan sebelumnya
4. Pada CTE mst_pizza_type isikan query pada **Bagian 4** yang sudah dikonstruksikan sebelumnya
5. Pada CTE mst_customer isikan query pada **Bagian 5** yang sudah dikonstruksikan sebelumnya
6. Relasikan semua CTE-nya (trx_order, trx_order_detail, mst_pizza, mst_pizza_type dan mst_customer) dengan kunci, penggunaan prefix dan metode join yang tepat
7. Tampilkan kolom
    * order_id,
    * order_details_id,
    * pizza_id,
    * customer_id,
    * order_maker_id,
    * order_date,
    * customer_name,
    * customer_gender,
    * customer_age,
    * customer_tenure_in_months,
    * pizza_name,
    * pizza_category,
    * pizza_size,
    * pizza_price,
    * pizza_production_cost,
    * quantity,
    * pizza_ingredients,
    * order_time,
    * completion_time,
    * duration_in_minutes,
    * is_complain,
    * complain_detail

In [88]:
%%bigquery --project {project_id} --verbose

WITH trx_order AS (
    SELECT
      order_id,
      customer_id,
      order_maker_id,
      PARSE_DATE('%m/%d/%Y', order_date) AS order_date,
      PARSE_TIME('%H:%M:%S', order_time) AS order_time,
      PARSE_TIME('%H:%M:%S', completion_time) AS completion_time,
      TIME_DIFF(PARSE_TIME('%H:%M:%S', completion_time), PARSE_TIME('%H:%M:%S', order_time), MINUTE) AS duration_in_minutes,
      is_complain,
      complain_detail
    FROM `dqpizza.transaction_order`
    WHERE order_id IS NOT NULL
),
trx_order_detail AS (
    SELECT
      order_details_id,
      order_id,
      pizza_id,
      quantity
    FROM `dqpizza.transaction_order_detail`
    WHERE order_id IS NOT NULL AND order_details_id IS NOT NULL
),
mst_pizza AS (
    SELECT
      pizza_id,
      pizza_type_id,
      UPPER(size) AS pizza_size,
      CAST(REPLACE(price, 'IDR', '') AS FLOAT64) AS pizza_price,
      CAST(REPLACE(production_cost, 'IDR', '') AS FLOAT64) AS pizza_production_cost
    FROM `dqpizza.master_pizza`
    WHERE pizza_id IS NOT NULL
),
mst_pizza_type AS (
    SELECT
      pizza_type_id,
      UPPER(name) AS pizza_name,
      UPPER(category) AS pizza_category,
      ingredients AS pizza_ingredients
    FROM `dqpizza.master_pizza_type`
    WHERE pizza_type_id IS NOT NULL
    GROUP BY ALL
),
mst_customer AS (
  SELECT DISTINCT
      customer_id,
      customer_name,
      gender AS customer_gender,
      DATE_DIFF(DATE '2025-12-31', COALESCE(SAFE.PARSE_DATE('%Y-%m-%d', birth_date), SAFE.PARSE_DATE('%m/%d/%Y', birth_date), SAFE.PARSE_DATE('%Y/%m/%d', birth_date)), YEAR) AS customer_age,
      DATE_DIFF(DATE '2025-12-31', COALESCE(SAFE.PARSE_DATE('%Y-%m-%d', open_date), SAFE.PARSE_DATE('%m/%d/%Y', open_date), SAFE.PARSE_DATE('%Y/%m/%d', open_date)), MONTH) AS customer_tenure_in_months
  FROM
      dqpizza.master_customer
  WHERE
      customer_id IS NOT NULL
)
SELECT
    o.order_id,
    od.order_details_id,
    od.pizza_id,
    o.customer_id,
    o.order_maker_id,
    o.order_date,
    c.customer_name,
    c.customer_gender,
    c.customer_age,
    c.customer_tenure_in_months,
    pt.pizza_name,
    pt.pizza_category,
    p.pizza_size,
    p.pizza_price,
    p.pizza_production_cost,
    od.quantity,
    pt.pizza_ingredients,
    o.order_time,
    o.completion_time,
    o.duration_in_minutes,
    o.is_complain,
    o.complain_detail
FROM trx_order AS o
INNER JOIN trx_order_detail AS od ON o.order_id = od.order_id
INNER JOIN mst_pizza AS p ON od.pizza_id = p.pizza_id
INNER JOIN mst_pizza_type AS pt ON p.pizza_type_id = pt.pizza_type_id
INNER JOIN mst_customer AS c ON o.customer_id = c.customer_id;

Executing query with job ID: 7c4961ec-a92a-4783-bcf6-4ab2661e0761
Query executing: 2.16s
Job ID 7c4961ec-a92a-4783-bcf6-4ab2661e0761 successfully executed

Query is running:   0%|          |

Downloading:   0%|          |

,order_id,order_details_id,pizza_id,customer_id,order_maker_id,order_date,customer_name,customer_gender,customer_age,customer_tenure_in_months,...,pizza_size,pizza_price,pizza_production_cost,quantity,pizza_ingredients,order_time,completion_time,duration_in_minutes,is_complain,complain_detail
0,TRX000802,TRXD001818,PIZZA_CKN_ALFREDO_S,CUST005956,EMP000208,2025-01-14,Gina Siregar,F,36,12,...,S,103275.00,78408.00,1,"Chicken, Red Onions, Red Peppers, Mushrooms, A...",13:23:47,13:49:28,26,0,None
1,TRX001256,TRXD002843,PIZZA_ITAL_SUPR_S,CUST004225,EMP000208,2025-01-22,Devi Andriani,F,43,11,...,S,101250.00,77598.00,1,"Calabrese Salami, Capocollo, Tomatoes, Red Oni...",12:06:15,12:25:06,19,0,None
2,TRX002077,TRXD004696,PIZZA_ITAL_SUPR_S,CUST005205,EMP000208,2025-02-04,Dwi Saefullah,M,28,11,...,S,101250.00,77598.00,1,"Calabrese Salami, Capocollo, Tomatoes, Red Oni...",14:31:27,14:57:02,26,0,None
3,TRX002379,TRXD005385,PIZZA_MEXICANA_S,CUST004778,EMP000208,2025-02-09,Galiono Nashiruddin,M,33,12,...,S,97200.00,72009.00,1,"Tomatoes, Red Peppers, Jalapeno Peppers, Red O...",16:18:14,16:44:48,26,0,None
4,TRX002486,TRXD005611,PIZZA_CKN_ALFREDO_L,CUST006034,EMP000208,2025-02-11,Jarwi Zulkarnain,M,29,12,...,L,168075.00,130410.00,1,"Chicken, Red Onions, Red Peppers, Mushrooms, A...",13:30:45,13:57:13,27,0,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48614,TRX002875,TRXD006492,PIZZA_VEGGIE_VEG_S,CUST005584,EMP000437,2025-02-17,Putri Natsir,F,33,11,...,S,97200.00,69093.00,1,"Mushrooms, Tomatoes, Red Peppers, Green Pepper...",19:26:46,19:40:23,14,1,Wrong pizza size
48615,TRX004912,TRXD011198,PIZZA_VEGGIE_VEG_S,CUST001220,EMP000560,2025-03-24,Cinta Widodo,F,45,11,...,S,97200.00,69093.00,1,"Mushrooms, Tomatoes, Red Peppers, Green Pepper...",16:58:45,17:12:16,14,1,Wrong pizza size
48616,TRX018642,TRXD042376,PIZZA_VEGGIE_VEG_S,CUST004020,EMP000646,2025-11-14,Luis Oktaviani,M,31,12,...,S,97200.00,69093.00,1,"Mushrooms, Tomatoes, Red Peppers, Green Pepper...",15:27:57,15:40:36,13,1,Wrong pizza size
48617,TRX007961,TRXD018138,PIZZA_VEGGIE_VEG_S,CUST001128,EMP000665,2025-05-14,Timbul Prayoga,M,35,12,...,S,97200.00,69093.00,1,"Mushrooms, Tomatoes, Red Peppers, Green Pepper...",13:04:17,13:26:36,22,1,Wrong pizza size
48618,TRX011092,TRXD025197,PIZZA_VEGGIE_VEG_S,CUST002637,EMP000665,2025-07-04,Jabal Padmasari,M,31,12,...,S,97200.00,69093.00,1,"Mushrooms, Tomatoes, Red Peppers, Green Pepper...",20:06:52,20:36:08,30,1,Wrong pizza size

Buumm.. semua tabel sudah terintegrasi dengan baik, saatnya load hasilnya ke tabel `tbl_detail_transaction`

<img src="https://raw.githubusercontent.com/bachtiyarwork/Image/main/DQPizza%20-%20Aksara%20Welcome.png" width="25%">

In [90]:
%%bigquery --project {project_id} --verbose

CREATE TABLE dqpizza.tbl_detail_transaction AS

WITH trx_order AS (
    SELECT
      order_id,
      customer_id,
      order_maker_id,
      PARSE_DATE('%m/%d/%Y', order_date) AS order_date,
      PARSE_TIME('%H:%M:%S', order_time) AS order_time,
      PARSE_TIME('%H:%M:%S', completion_time) AS completion_time,
      TIME_DIFF(PARSE_TIME('%H:%M:%S', completion_time), PARSE_TIME('%H:%M:%S', order_time), MINUTE) AS duration_in_minutes,
      is_complain,
      complain_detail
    FROM `dqpizza.transaction_order`
    WHERE order_id IS NOT NULL
),
trx_order_detail AS (
    SELECT
      order_details_id,
      order_id,
      pizza_id,
      quantity
    FROM `dqpizza.transaction_order_detail`
    WHERE order_id IS NOT NULL AND order_details_id IS NOT NULL
),
mst_pizza AS (
    SELECT
      pizza_id,
      pizza_type_id,
      UPPER(size) AS pizza_size,
      CAST(REPLACE(price, 'IDR', '') AS FLOAT64) AS pizza_price,
      CAST(REPLACE(production_cost, 'IDR', '') AS FLOAT64) AS pizza_production_cost
    FROM `dqpizza.master_pizza`
    WHERE pizza_id IS NOT NULL
),
mst_pizza_type AS (
    SELECT
      pizza_type_id,
      UPPER(name) AS pizza_name,
      UPPER(category) AS pizza_category,
      ingredients AS pizza_ingredients
    FROM `dqpizza.master_pizza_type`
    WHERE pizza_type_id IS NOT NULL
    GROUP BY ALL
),
mst_customer AS (
  SELECT DISTINCT
      customer_id,
      customer_name,
      gender AS customer_gender,
      DATE_DIFF(DATE '2025-12-31', COALESCE(SAFE.PARSE_DATE('%Y-%m-%d', birth_date), SAFE.PARSE_DATE('%m/%d/%Y', birth_date), SAFE.PARSE_DATE('%Y/%m/%d', birth_date)), YEAR) AS customer_age,
      DATE_DIFF(DATE '2025-12-31', COALESCE(SAFE.PARSE_DATE('%Y-%m-%d', open_date), SAFE.PARSE_DATE('%m/%d/%Y', open_date), SAFE.PARSE_DATE('%Y/%m/%d', open_date)), MONTH) AS customer_tenure_in_months
  FROM
      dqpizza.master_customer
  WHERE
      customer_id IS NOT NULL
)
SELECT
    o.order_id,
    od.order_details_id,
    od.pizza_id,
    o.customer_id,
    o.order_maker_id,
    o.order_date,
    c.customer_name,
    c.customer_gender,
    c.customer_age,
    c.customer_tenure_in_months,
    pt.pizza_name,
    pt.pizza_category,
    p.pizza_size,
    p.pizza_price,
    p.pizza_production_cost,
    od.quantity,
    pt.pizza_ingredients,
    o.order_time,
    o.completion_time,
    o.duration_in_minutes,
    o.is_complain,
    o.complain_detail
FROM trx_order AS o
INNER JOIN trx_order_detail AS od ON o.order_id = od.order_id
INNER JOIN mst_pizza AS p ON od.pizza_id = p.pizza_id
INNER JOIN mst_pizza_type AS pt ON p.pizza_type_id = pt.pizza_type_id
INNER JOIN mst_customer AS c ON o.customer_id = c.customer_id;

Executing query with job ID: 61e216d0-156b-48d5-9ea8-99bcf3cac281
Query executing: 3.07s
Job ID 61e216d0-156b-48d5-9ea8-99bcf3cac281 successfully executed

Query is running:   0%|          |

Empty DataFrame
Columns: []
Index: []

Pastikan tabel sudah benar-benar terbentuk dan akses tabelnya untuk memastikan

In [ ]:
%%bigquery --project {project_id} --verbose

SELECT
  *
FROM dqpizza.tbl_detail_detail

Executing query with job ID: d993a647-582b-4491-9453-628b1f2dbe1a
Query executing: 1.60s
Job ID d993a647-582b-4491-9453-628b1f2dbe1a successfully executed

Query is running:   0%|          |

Downloading:   0%|          |

,order_id,order_details_id,pizza_id,customer_id,order_maker_id,order_date,customer_name,customer_gender,customer_age,customer_tenure_in_months,...,pizza_size,pizza_price,pizza_production_cost,quantity,pizza_ingredients,order_time,completion_time,duration_in_minutes,is_complain,complain_detail
0,TRX013735,TRXD031103,PIZZA_BBQ_CKN_L,CUST002835,EMP000295,2025-08-17,Adinata Tamba,M,51,11,...,L,168075.00,133245.00,1,"Barbecued Chicken, Red Peppers, Green Peppers,...",14:42:38,15:04:55,22,0,None
1,TRX016516,TRXD037417,PIZZA_BBQ_CKN_L,CUST002835,EMP000646,2025-10-06,Adinata Tamba,M,51,11,...,L,168075.00,133245.00,1,"Barbecued Chicken, Red Peppers, Green Peppers,...",15:10:43,15:33:39,23,0,None
2,TRX001090,TRXD002450,PIZZA_BBQ_CKN_L,CUST002835,EMP000437,2025-01-19,Adinata Tamba,M,51,11,...,L,168075.00,133245.00,1,"Barbecued Chicken, Red Peppers, Green Peppers,...",12:14:24,12:40:51,26,0,None
3,TRX005336,TRXD012151,PIZZA_BBQ_CKN_L,CUST002835,EMP000560,2025-03-31,Adinata Tamba,M,51,11,...,L,168075.00,133245.00,1,"Barbecued Chicken, Red Peppers, Green Peppers,...",15:32:39,15:55:36,23,0,None
4,TRX018205,TRXD041351,PIZZA_BBQ_CKN_L,CUST002835,EMP000756,2025-11-06,Adinata Tamba,M,51,11,...,L,168075.00,133245.00,1,"Barbecued Chicken, Red Peppers, Green Peppers,...",20:45:57,21:05:31,20,0,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48614,TRX005110,TRXD011627,PIZZA_VEGGIE_VEG_S,CUST007482,EMP000560,2025-03-27,Zulaikha Yuliarti,F,31,12,...,S,97200.00,69093.00,1,"Mushrooms, Tomatoes, Red Peppers, Green Pepper...",18:26:20,18:53:34,27,0,None
48615,TRX016225,TRXD036761,PIZZA_VEGGIE_VEG_S,CUST007482,EMP000302,2025-09-30,Zulaikha Yuliarti,F,31,12,...,S,97200.00,69093.00,1,"Mushrooms, Tomatoes, Red Peppers, Green Pepper...",20:11:25,20:35:45,24,0,None
48616,TRX019679,TRXD044784,PIZZA_VEGGIE_VEG_S,CUST007482,EMP000646,2025-12-01,Zulaikha Yuliarti,F,31,12,...,S,97200.00,69093.00,1,"Mushrooms, Tomatoes, Red Peppers, Green Pepper...",12:21:24,12:46:12,25,0,None
48617,TRX003589,TRXD008182,PIZZA_VEGGIE_VEG_S,CUST007482,EMP000665,2025-03-02,Zulaikha Yuliarti,F,31,12,...,S,97200.00,69093.00,1,"Mushrooms, Tomatoes, Red Peppers, Green Pepper...",12:46:49,13:09:55,23,0,None
48618,TRX020684,TRXD047065,PIZZA_VEGGIE_VEG_S,CUST007482,EMP000756,2025-12-17,Zulaikha Yuliarti,F,31,12,...,S,97200.00,69093.00,1,"Mushrooms, Tomatoes, Red Peppers, Green Pepper...",19:26:31,19:48:35,22,0,None

Sip ini langkah awal yang baik, sudah selesai semua 'dimasak' kini saatnya melangkah lebih jauh lagi. Silahkan akses link <a href="https://colab.research.google.com/drive/1qc4Gn4I4ezJC0FHqsN3qybQF9gxAQYxK#scrollTo=C-J5r46BcL-q$0">berikut</a>.

Data Source : <i>https://mavenanalytics.io/challenges/maven-pizza-challenge</i> (dengan modifikasi)


---
<br>
<a href="https://dqlab.id/"><img src="https://dqlab.id/files/dqlab/cache/87e30118ebba5ec7d96f6ea8c9dcc10b_x_118_X_55.png" align="left" /></a>